import React from "react";
import "./globals.css";
import ReduxProvider from "@/store/provider";

export const metadata = {
  title: "My Next App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
